# Generated by Django 5.2.15 on 2026-07-02 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('ordonnance', models.ImageField(blank=True, null=True, upload_to='ordonnances/')),
                ('numero_scelle', models.CharField(blank=True, max_length=30)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('validee', 'Validée par la pharmacie'), ('preparee', 'Scellée et prête'), ('en_livraison', 'En cours de livraison'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('mode_livraison', models.CharField(choices=[('retrait', 'Retrait en pharmacie'), ('livraison', 'Livraison à domicile')], max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='pharmacies.stock')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-date_creation'],
            },
        ),
    ]
