# Generated by Django 5.2.15 on 2026-07-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='adresse_livraison',
            field=models.CharField(blank=True, help_text='Quartier + repère (ex: Dixinn, près de la pharmacie Bonfi), requis pour une livraison à domicile.', max_length=255),
        ),
    ]
