# Generated by Django 5.2.15 on 2026-07-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_commercial', models.CharField(max_length=150)),
                ('dci', models.CharField(max_length=150, verbose_name='Dénomination Commune Internationale')),
                ('categorie', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('est_sur_ordonnance', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='medicaments/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Médicament',
                'verbose_name_plural': 'Médicaments',
                'ordering': ['nom_commercial'],
                'indexes': [models.Index(fields=['nom_commercial'], name='medicaments_nom_com_226d69_idx'), models.Index(fields=['dci'], name='medicaments_dci_1b3ebc_idx')],
            },
        ),
    ]
