# Generated by Django 5.2.15 on 2026-07-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='cle_recherche',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=310),
        ),
    ]
