# Generated by Django 5.2.15 on 2026-07-02 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('quartier', models.CharField(choices=[('kaloum', 'Kaloum'), ('ratoma', 'Ratoma'), ('matoto', 'Matoto'), ('dixinn', 'Dixinn'), ('matam', 'Matam')], max_length=50)),
                ('adresse', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('numero_agrement_onpg', models.CharField(max_length=50, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('est_de_garde', models.BooleanField(default=False, verbose_name='De garde actuellement')),
                ('est_verifiee', models.BooleanField(default=False, verbose_name="Vérifiée par l'ONPG/DNPM")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pharmacie',
                'verbose_name_plural': 'Pharmacies',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_disponible', models.PositiveIntegerField(default=0)),
                ('prix_unitaire_gnf', models.PositiveIntegerField(verbose_name='Prix unitaire (GNF)')),
                ('date_derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='medicaments.medicament')),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='pharmacies.pharmacie')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'indexes': [models.Index(fields=['medicament', 'quantite_disponible'], name='pharmacies__medicam_177e1b_idx')],
                'unique_together': {('pharmacie', 'medicament')},
            },
        ),
    ]
