"""
Django settings for pharmguineefm project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# La clé et tous les réglages sensibles viennent maintenant du fichier .env
# (jamais versionné dans Git, voir .gitignore), lu grâce à python-decouple.
# En local, un fichier .env.example montre quelles variables définir.
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='127.0.0.1,localhost', cast=Csv())

# --- Sécurité en production -------------------------------------------------
# Ces réglages ne s'activent que quand DEBUG=False (donc jamais en local avec
# runserver, où il n'y a pas de HTTPS). C'est important : la plateforme
# traite des données médicales (ordonnances, historique de commandes), donc
# on force le chiffrement des échanges dès que le site est réellement en ligne.
#
# SECURE_PROXY_SSL_HEADER est nécessaire sur PythonAnywhere : leur serveur
# gère le certificat HTTPS et relaie ensuite la requête à Django avec un
# en-tête "X-Forwarded-Proto". Sans ce réglage, Django croirait que toutes
# les requêtes arrivent en HTTP (même si le visiteur est bien en HTTPS) et
# SECURE_SSL_REDIRECT créerait une boucle de redirection infinie.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
# HSTS : dit au navigateur de refuser de revenir en HTTP pendant 1h après
# une première visite en HTTPS. Valeur volontairement modeste pour l'instant
# (à augmenter plus tard une fois le HTTPS bien confirmé stable).
SECURE_HSTS_SECONDS = 3600 if not DEBUG else 0


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Django REST Framework : fournit les outils pour construire l'API
    'rest_framework',

    # Applications propres au projet PharmGuinéeFM / PharmaSila
    'patients',
    'pharmacies',
    'medicaments',
    'commandes',
    'ministere',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pharmguineefm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pharmguineefm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# SQLite reste la base par défaut pour l'instant : le MySQL fourni par MAMP
# (5.7) est trop ancien pour Django 5.2 (il faut 8.0+), et les comptes
# gratuits PythonAnywhere créés après janvier 2026 n'incluent plus MySQL
# (réservé à l'offre payante Developer). SQLite tient très bien la charge
# pour un projet pilote. DB_ENGINE=mysql dans le .env permet de basculer
# plus tard, si un hébergement avec MySQL 8+ est disponible.
if config('DB_ENGINE', default='sqlite') == 'sqlite':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': config('DB_NAME'),
            'USER': config('DB_USER'),
            'PASSWORD': config('DB_PASSWORD'),
            'HOST': config('DB_HOST', default='127.0.0.1'),
            'PORT': config('DB_PORT', default='3306'),
            'OPTIONS': {
                # utf8mb4 : jeu de caractères complet, nécessaire pour bien
                # stocker les accents français et les éventuels emojis
                'charset': 'utf8mb4',
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Redirections liées à l'authentification (comptes patients)
LOGIN_URL = 'patients:connexion'
LOGIN_REDIRECT_URL = 'accueil'
LOGOUT_REDIRECT_URL = 'accueil'

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# Site en français (langue des patients et des pharmaciens guinéens)
LANGUAGE_CODE = 'fr-fr'

# Fuseau horaire de Conakry (GMT, pas de changement d'heure en Guinée)
TIME_ZONE = 'Africa/Conakry'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Dossier où "collectstatic" rassemble tous les fichiers statiques avant le
# déploiement (nécessaire en production ; en local avec runserver, Django
# sert les fichiers directement sans passer par ce dossier).
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Fichiers envoyés par les utilisateurs (photos de médicaments, ordonnances)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
