"""
Django settings for pharmguineefm project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')  # tout le sensible est dans .env, jamais versionné (cf .gitignore)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='127.0.0.1,localhost', cast=Csv())

# --- sécu prod, actif seulement si DEBUG=False (jamais en local, pas de HTTPS avec runserver) ---
# données médicales dedans (ordonnances, commandes) donc on force le chiffrement en ligne
#
# SECURE_PROXY_SSL_HEADER obligatoire sur PythonAnywhere : leur proxy termine le HTTPS puis
# relaie en HTTP avec un header X-Forwarded-Proto. Sans ça Django pense que tout arrive en HTTP
# et SECURE_SSL_REDIRECT part en boucle de redirection infinie.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_HSTS_SECONDS = 3600 if not DEBUG else 0  # 1h pour l'instant, à monter une fois le HTTPS stable confirmé

# --- emails (notif de suivi de commande à chaque changement de statut) ---
# DEBUG=True : rien n'est vraiment envoyé, Django affiche juste dans le terminal (backend console)
# prod : SMTP Gmail avec mot de passe d'application (jamais le vrai mdp, voir .env.example)
EMAIL_BACKEND = config(
    'EMAIL_BACKEND',
    default='django.core.mail.backends.console.EmailBackend'
    if DEBUG
    else 'django.core.mail.backends.smtp.EmailBackend',
)
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config(
    'DEFAULT_FROM_EMAIL', default='PharmaSila Guinée <no-reply@pharmasila.gn>'
)

# Brevo en HTTPS (cf commandes/notifications.py) contourne le blocage SMTP PythonAnywhere gratuit.
# vide en local -> retombe sur EMAIL_BACKEND ci-dessus
BREVO_API_KEY = config('BREVO_API_KEY', default='')
BREVO_SENDER_EMAIL = config('BREVO_SENDER_EMAIL', default='')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Django REST Framework : fournit les outils pour construire l'API
    'rest_framework',

    # Applications propres au projet PharmGuinéeFM / PharmaSila
    'patients',
    'pharmacies',
    'medicaments',
    'commandes',
    'ministere',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pharmguineefm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pharmguineefm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# SQLite pour l'instant : le MySQL de MAMP (5.7) est trop vieux pour Django 5.2 (faut 8.0+),
# et PythonAnywhere gratuit n'inclut plus MySQL depuis janv. 2026. Suffit largement pour un pilote.
# DB_ENGINE=mysql dans .env pour basculer si un hébergement MySQL 8+ arrive.
if config('DB_ENGINE', default='sqlite') == 'sqlite':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': config('DB_NAME'),
            'USER': config('DB_USER'),
            'PASSWORD': config('DB_PASSWORD'),
            'HOST': config('DB_HOST', default='127.0.0.1'),
            'PORT': config('DB_PORT', default='3306'),
            'OPTIONS': {
                'charset': 'utf8mb4',  # sinon soucis avec les accents français
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Redirections liées à l'authentification (comptes patients)
LOGIN_URL = 'patients:connexion'
LOGIN_REDIRECT_URL = 'accueil'
LOGOUT_REDIRECT_URL = 'accueil'

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# Site en français (langue des patients et des pharmaciens guinéens)
LANGUAGE_CODE = 'fr-fr'

# Fuseau horaire de Conakry (GMT, pas de changement d'heure en Guinée)
TIME_ZONE = 'Africa/Conakry'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Dossier où "collectstatic" rassemble tous les fichiers statiques avant le
# déploiement (nécessaire en production ; en local avec runserver, Django
# sert les fichiers directement sans passer par ce dossier).
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Fichiers envoyés par les utilisateurs (photos de médicaments, ordonnances)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
